#!/usr/bin/env bash
# Cilium replaces kube-proxy, so every machine config must say `proxy.disabled = true`. CI used to
# assert it with `grep -q 'disabled: true'` on a config generated by plain `talosctl gen config`:
# that file never carried this repository's patch, and the match was the Kubernetes discovery
# registry's own `disabled: true`, which Talos 1.14 stopped writing, so the step broke on the bump
# and had never tested kube-proxy at all. This reads the patches the module builds. SUT overrides
# the file, which is how the mutants run.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SUT="${SUT:-$ROOT/infrastructure/opentofu/modules/talos/main.tf}"
PASS=0; FAIL=0
ok()  { printf '  \033[32m✓\033[0m %s\n' "$*"; PASS=$((PASS + 1)); }
bad() { printf '  \033[31m✗\033[0m %s\n' "$*"; FAIL=$((FAIL + 1)); }

# `proxy = {` followed, before its closing brace, by `disabled = true`; one per machine type.
blocks() { awk '/^[[:space:]]*proxy[[:space:]]*=[[:space:]]*\{/ { on = 1; next }
                on && /disabled[[:space:]]*=[[:space:]]*true/ { print "true"; on = 0; next }
                on && /disabled[[:space:]]*=[[:space:]]*false/ { print "false"; on = 0; next }
                on && /\}/ { print "absent"; on = 0 }' "$SUT"; }
R="$(blocks | tr '\n' ' ')"
[ "$(wc -w <<<"$R")" -ge 2 ] && ok "the module sets a proxy block for the control planes and for the workers ($R)" \
  || bad "expected a proxy block in both the control plane and the worker patch, found: [$R]"
grep -qE 'false|absent' <<<"$R" && bad "a proxy block does not disable kube-proxy: [$R]" || ok "every proxy block disables kube-proxy"

printf '%s passed, %s failed\n' "$PASS" "$FAIL"
[ "$PASS" -gt 0 ] && [ "$FAIL" -eq 0 ]
